spring:
  application:
    name: bifrost-sample
  ai:
    ollama:
      enabled: true
      base-url: http://localhost:11434
      #base-url: http://192.168.4.83:11434
      chat:
        options:
          model: ibm/granite4:tiny-h
          #model: gemma4:26b
          #model: gemma4:e4b
          temperature: 0.7

server:
  port: 8081

logging:
  level:
    com.lokiscale.bifrost.sample: INFO
    com.lokiscale.bifrost.chat: DEBUG
    com.lokiscale.bifrost.linter: DEBUG
    com.lokiscale.bifrost.outputschema: DEBUG
    com.lokiscale.bifrost.runtime.planning: DEBUG
    org.springframework.ai.chat.client: DEBUG

bifrost:
  session:
    mission-timeout: 6000s
  skills:
    locations:
      - classpath:/skills/**/*.yml
      - classpath:/skills/**/*.yaml
  models:
    granite4-tiny:
      provider: ollama
      provider-model: ibm/granite4:tiny-h
    gemma4-e2b:
      provider: ollama
      provider-model: gemma4:e2b
    gemma4-26b:
      provider: ollama
      provider-model: gemma4:26b
    gemma4-e4b:
      provider: ollama
      provider-model: gemma4:e4b
    default-model:
      provider: ollama
      provider-model: ibm/granite4:tiny-h

execution-trace:
  persistence: ALWAYS
